### ISSUE TITLE
Unexpceted Status Value

### ISSUE THREAD

**Issue by pcud** [dansmith65/FileMaker-LetsEncrypt-Win#17]
Hello!

First, thanks for creating this, it is honestly wonderful and I have now set this up on many different windows servers and this is the first time I've fun into a problem. When I run the script, I'm getting the below error. The only thing of note is that I have ~8 subdomains I'm setting up on this one server. I looked at the script myself and it seems super well formatted, but I have almost no knowledge of ps1 scripts. Any help would be very much appreciated.

unexpected status value
At C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1:680 char:3
+         throw ("unexpected status value")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (unexpected status value:String) [], RuntimeException
    + FullyQualifiedErrorId : unexpected status value

**Comment by dansmith65** [comment]
That doesn't provide the info necessary for me to debug this issue. If you send me the log file from this failed run, I'll do what I can to help.

**Comment by pcud** [comment]
Thank you. However I'm not sure which would log the relevant information for you. None of the FileMaker logs recorded anything relevant and I don't see any log file that might be outputted from your script. Is there a windows log that you would find helpful?

**Comment by dansmith65** [comment]
When you run the script it tells you where it writes logs, but the default locations is:

    C:\Program Files\FileMaker\FileMaker Server\Data\Documents\GetSSL.ps1\

Have a look at the log before sending it to me to confirm it contains the error message you saw. A new log is created each time the script runs, so if you ran the script since that error, the log I need to see won't be the newest one.

**Comment by pcud** [comment]
Ah. I see that it does state that when it's run. I did a fresh run today and got the same error. Here's a wetransfer link to the log file.
https://we.tl/t-Spi22PM7it

**Comment by dansmith65** [comment]
Have a look at that log yourself, there are a bunch of errors starting at line 171. Note that your server will need to be accessible from all the domains that you want to include in the certificate, which doesn't seem to be the case right now.
