### ISSUE TITLE
Are wildcards supported?

### ISSUE THREAD

**Issue by ACSMid** [dansmith65/FileMaker-LetsEncrypt-Win#18]
This script works great with filemaker.acme.com, but gives this lovely message when I try and use *.acme.com. Am I doing something wrong or are wildcards simply not supported?

Get-KeyAuthorization : Cannot bind argument to parameter 'Token' because it is an empty string.
At D:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1:658 char:32
        $body = Get-KeyAuthorization $auth.HTTP01Token $account

     CategoryInfo          : InvalidData: (:) [Get-KeyAuthorization], ParentContainsErrorRecordException
     FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-KeyAuthorization

**Comment by dansmith65** [comment]
At the time I wrote this script, I don't think Let's Encrypt even supported wildcards, it looks like they do now, but only via DNS challenge, which this script doesn't use: https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates

An alternative would be to specify multiple domains, which isn't the same thing, but is as close as this project can get.

**Comment by ACSMid** [comment]
Thanks Dan. Great work by the way. I have "Certify Certificate Manager" updating the cert now. It puts it in local computer\personal\certificates. If there was a project that took it from there and put it in FileMaker that would also accomplish what I'm looking for. I'll see if I can't find something that does this.

**Comment by dansmith65** [comment]
You can probably use my script as a starting point for automating the installation to FileMaker. It seems like that app has scripting options, including a post-request task: https://docs.certifytheweb.com/docs/script-hooks#deployment-tasks-post-request

**Comment by ACSMid** [comment]
That was my thinking as well. I made a little script that does it now I'm good to go.

**Comment by dataperformance** [comment]
I've been using this script for years and I love it (thank you Dan Smith)! However, I'd like to use a wildcard cert. Could you share your script, ACSMid?

**Comment by ACSMid** [comment]
Sure. It works, but it's not finished. It doesn't delete the pem files yet. Perhaps the next time the cert is refreshed it will overwrite the old one. This still needs tested.  I won't implement this until I'm sure it's working the way I want. I also need to figure out how Dan used the Windows cert manager to store the passwords as well. I just have them as part of the script until I do that.

Also a prerequisite is that you use Certify Certificate Manager to update the cert. Then use a post-request task with task type "Deploy to Generic Server" with a task parameter of "C:\Filemaker Certs\cert.pem" without the quotes.

`#Certify Certificate Manager puts the cert.pem and key.pem files in the FileMaker Certs folder after renewing the cert.

#Set variables
$fmsadmin = 'D:\Program Files\FileMaker\FileMaker Server\Database Server\fmsadmin.exe'
$certPath = 'C:\Filemaker Certs\cert.pem'
$userAndPassParamString = "-u xxxx -p xxxx"

#Import cert into FileMaker
cmd /c "`"$fmsadmin`" certificate import `"$certPath`" -y $userAndPassParamString"

#Restart FileMaker
Restart-Service -Name 'FileMaker Server' -Force`

**Comment by dataperformance** [comment]
👍👍
