### ISSUE TITLE
System.UnauthorizedAccessException,ACMESharp.POSH.SubmitCertificate

### ISSUE THREAD

**Issue by dansmith65** [dansmith65/FileMaker-LetsEncrypt-Win#3]
On the first scheduled task run on a production server, I got this error: 

> Submit-ACMECertificate : Access to the path 'C:\ProgramData\ACMESharp\sysVault\{redacted}\{redacted}-key.pem' is denied.
> At C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1:589 char:3
> FullyQualifiedErrorId : System.UnauthorizedAccessException,ACMESharp.POSH.SubmitCertificate

Which is documented here: https://pkisharp.github.io/ACMESharp-docs/Local-Vault-EFS.html

But has never occurred on this server, or any similarly configured server until now. I manually completed the install (by looking at what the script was supposed to do, and running those steps in PowerShell). I had to add a `-Force` parameter to the `Submit-ACMECertificate` step to get it to work after the above error.

Not sure what to do about this bug. I'm going to monitor for it on the next certificate renewal and take it from there.

**Comment by dansmith65** [comment]
This issue was also mentioned here: http://disq.us/p/1t412p1, which said to follow these directions: https://blogs.technet.microsoft.com/askds/2008/01/07/replacing-an-expired-dra-certificate/

But the server this affected didn't have a DRA Certificate.

**Comment by a-fanet** [comment]
I've been running to this as well. Tried resetting the DRA certificate and didn't seem to work.

**Comment by a-fanet** [comment]
Following up here, still a bug for me even after trying to set up efs and adding the force parameter

**Comment by dansmith65** [comment]
Sorry, I really don't know what else could be causing this. Have you checked with the ACMESharp project? This repo is just a wrapper for that, which is the one returning the error, someone there might have more info for you.

One thought is to try forking this repo and switching out the method of communicating with Let's Encrypt. It looks like there are a few other alternatives out there now:

- https://github.com/PKISharp/ACMESharpCore-PowerShell
- https://github.com/PKISharp/win-acme

Not that this _will_ solve you issue; it's just a possible avenue to test.
