### ISSUE TITLE
Split-Path error relating to log directory

### ISSUE THREAD

**Issue by jeremy-hunter** [dansmith65/FileMaker-LetsEncrypt-Win#4]
Hi - thank you for this script, it's a timesaver :)

I am getting an error when running the script:
```
PS C:\installers> C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1
cmdlet GetSSL.ps1 at command pipeline position 1
Supply values for the following parameters:
Domains[0]: xyz.abc.com
Domains[1]: 
Email: email@domain.com
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1:150 char:54
+ ... (Split-Path (Get-Variable MyInvocation -Scope 0).Value.MyCommand.Path ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
```
I changed 
`[string] $LogDirectory = "$(Split-Path $(Split-Path (Get-Variable MyInvocation -Scope 0).Value.MyCommand.Path))\Documents\$($MyInvocation.MyCommand.Name)",`
to
`[string] $LogDirectory = "",`
...and it started working

Still works great, just wanted to bring this to your attention 👍

**Comment by dansmith65** [comment]
Thanks for letting me know about this.

With that change, where are the log files created? If you don't specify a logDirectory, I'm assuming they'll be in the same directory as the script, but I haven't tested.

I suspect this has something to do with a difference in versions of PowerShell, can you run this in PowerShell and send me the ouput?

    $PSVersionTable.PSVersion

This is what I get from two different system's I've tested this script on:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  2828
```

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  590
```

**Comment by dansmith65** [comment]
closed due to inactivity
