### ISSUE TITLE
ACMEv1: Account creation disabled

### ISSUE THREAD

**Issue by cwbsl** [dansmith65/FileMaker-LetsEncrypt-Win#5]
When trying to receive a certificate the following error is thrown:

```
New-ACMERegistration : Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
In C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1:498 Zeichen:3
+         New-ACMERegistration -Contacts mailto:$Email -AcceptTos
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (ACMESharp.Vault.Model.RegistrationInfo:RegistrationInfo) [New-ACMERegistration], AcmeWebException
    + FullyQualifiedErrorId : urn:acme:error:unauthorized (403),ACMESharp.POSH.NewRegistration
```

ACMEv1 is now disabled and v2 needs to be used instead so unfortunately those great scripts don't work anymore.

**Comment by dansmith65** [comment]
I had actually heard about this recently. I just started transitioning the underlying ACME client to https://github.com/rmbolger/Posh-ACME, which is v2 compatible. I'm not sure how long this change will take me, but I'll close this task when it's done.

**Comment by cwbsl** [comment]
Wow great! Keep up this great work!

**Comment by conroyke56** [comment]
Hey, any update on if this is likely to be resolved? or is there another way to make it work?

Cheers,

**Comment by dansmith65** [comment]
I think it's close but I have some testing to do. Want to test a pre
release version today?

**Comment by conroyke56** [comment]
yeh, would be happy to.
Cheers,

**Comment by dansmith65** [comment]
Here you go:

1. Download the `GetSSL.ps1` file to your server:

   ```powershell
   Invoke-WebRequest `
     -Uri https://raw.githubusercontent.com/dansmith65/FileMaker-LetsEncrypt-Win/dev/GetSSL.ps1 `
     -OutFile "C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1"
   ```

2. Install Dependencies:

   ```powershell
   Set-ExecutionPolicy Bypass -Scope Process -Force;
   & 'C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1'
   ```

3. Keep following the prompts to install a certificate, then schedule a task, then configure emailing you logs.

Documentation hasn't been updated yet. The script header or `Get-Help` is more accurate, but even that isn't complete yet.

Let me know if you run into any errors.

**Comment by cwbsl** [comment]
Thanks a lot for providing the pre-release file to us!
I tried it and got this error:

![image](https://user-images.githubusercontent.com/37547654/69521985-8b813800-0f60-11ea-86f2-228c56322a6c.png)

**Comment by ameeyakumardas007** [comment]
Thank you so much for this amazing script! Great job! Here are my test results.

- Renewing certificates worked perfectly!
- Faced the same issue mentioned by @cwbsl in the above post when trying to install a new SSL certificate on a brand new server.

Again, thank you very much for making our lives easier!

**Comment by ameeyakumardas007** [comment]
> Thank you so much for this amazing script! Great job! Here are my test results.
> 
> * Renewing certificates worked perfectly!
> * Faced the same issue mentioned by @cwbsl in the above post when trying to install a new SSL certificate on a brand new server.
> 
> Again, thank you very much for making our lives easier!

Detailed steps:

- Install correct version of .NET framework required by Posh-ACME.
	-- Minimum required version: v4.7.1
	-- .NET Version Inquiry Link: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#ps_a
	-- Installation Link: https://www.microsoft.com/en-us/download/details.aspx?id=56116
- Install Posh-ACME
	-- Project Link: https://github.com/rmbolger/Posh-ACME
	-- PowerShell Installation Command: Install-Module -Name Posh-ACME
- Install CredentialManager
	-- PowerShell Gallery Link: https://www.powershellgallery.com/packages/CredentialManager/2.0
	-- PowerShell Installation Command: Install-Module -Name CredentialManager
- PowerShell Config
	-- Set-ExecutionPolicy Bypass -Scope Process -Force
- Ran the following command.
	-- "C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1" <dns> <support_email> -Staging
	-- Everything successful.
	-- "C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1" <dns> <support_email>
	-- Restarted the FMS service manually (just to make sure).

**Comment by dansmith65** [comment]
With any luck, the issue you both ran into is fixed. You can test by downloading again, then calling with `-Renew` parameter (and `-Staging` if you used it last time).

@ameeyakumardas007 To clarify, you don't have to manually install dependencies; the script will do that for you. You just call it with the new `-InstallDependencies` switch (or without any parameters, as install dependencies is the default action).

Regarding installing .NET Framework; this is currently optional because the Posh-ACME project has a custom build that doesn't require v4.7.1, like the main branch does. If the author ever stops supporting that version, I'll stop supporting it as well. https://github.com/rmbolger/Posh-ACME/wiki/Frequently-Asked-Questions-(FAQ)#azure-automation-or-my-environment-only-supports-net-46

**Comment by ameeyakumardas007** [comment]
Thanks @dansmith65. This worked like a charm! I was able to successfully able to install a certificate to a brand new server! 😃
Initially, when I had run the script, it threw some well-known exceptions. So I Googled a bit and find some solutions which were mainly related to Posh-ACME. So I wrote those steps here. Again, thanks for clarifying.

**Comment by petrowsky** [comment]
Things worked out on my end once the dependencies were installed. Great contribution to the community Dan!
