### ISSUE TITLE
Dev branch - Unexpected Status value

### ISSUE THREAD

**Issue by JoshTickles** [dansmith65/FileMaker-LetsEncrypt-Win#7]
Hey, 

Just something I am hitting on dev brach when trying to use the new POSHACME version.

```
Wednesday, 11 December 2019 9:39:49 AM

Delete old Log files, if necessary.

unexpected status value
At C:\Program Files\FileMaker\FileMaker Server\Data\Scripts\GetSSL.ps1:651 char:3
+         throw ("unexpected status value")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (unexpected status value:String) [], RuntimeException
    + FullyQualifiedErrorId : unexpected status value
```

Any advice on what could be going wrong here? It looks like I get the cert all okay, then error out when checking if it is valid?

Let me know if I can provide you more information.

Cheers.

**Comment by JoshTickles** [comment]
Update - This seems to only happen if I request 2 hostnames on the certificate.

**Comment by JoshTickles** [comment]
Ignore for now. I am having issues reliably re-creating the issue on each run.

**Comment by dansmith65** [comment]
First off, make sure you've got the latest copy from Dev branch. You probably do, but earlier alpha releases had this issue, so I wanted to double-check.

Next, I have had issues with properly testing the status and I think I've experienced intermittent errors myself. I thought I had fixed all of those, but can you check your logs to see what it reported right before the error? It's supposed to display the object's it found with the unexpected status value, and knowing what those object's look like will help me debug. You can email them directly to me if you'd like. You can also delete domains, id's etc. I mostly want to know what status value _was_ found.
