### ISSUE TITLE
Staging works perfectly, Actual throws error 379 char 9 :(

### ISSUE THREAD

**Issue by conroyke56** [dansmith65/FileMaker-LetsEncrypt-Win#9]
Again, is this an error in the script or something I'm doing wrong.

Staging works perfectly.

![getssl](https://user-images.githubusercontent.com/33205454/75840868-671ade80-5e20-11ea-9b93-f726e9a846bb.PNG)

**Comment by dansmith65** [comment]
Sorry, yet another bug that recently created. I just fixed that one in the latest commit. I ran this version to update my own certificate.

**Comment by conroyke56** [comment]
worked a charm! love it!
Thanks for all your efforts!
Github really needs a donate button.
